//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMS_Server.Res.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICMS_Server.Res.language.resLang", typeof(resLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        internal static string _return {
            get {
                return ResourceManager.GetString("return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลคูปอง.
        /// </summary>
        internal static string add_coupon {
            get {
                return ResourceManager.GetString("add_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม /แก้ไข ข้อมูลโบนัส.
        /// </summary>
        internal static string add_edit_bonus {
            get {
                return ResourceManager.GetString("add_edit_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม / แก้ไข ข้อมูลคูปอง.
        /// </summary>
        internal static string add_edit_coupon {
            get {
                return ResourceManager.GetString("add_edit_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม / แก้ไข ข้อมูลกลุ่มผู้ใช้.
        /// </summary>
        internal static string add_edit_group {
            get {
                return ResourceManager.GetString("add_edit_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม /แก้ไข ข้อมูลสมาชิก.
        /// </summary>
        internal static string add_edit_member {
            get {
                return ResourceManager.GetString("add_edit_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม /แก้ไข ข้อมูลโปรโมชั่น.
        /// </summary>
        internal static string add_edit_promo {
            get {
                return ResourceManager.GetString("add_edit_promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม / แก้ไข ข้อมูลพนักงาน.
        /// </summary>
        internal static string add_edit_staff {
            get {
                return ResourceManager.GetString("add_edit_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชั่วโมง.
        /// </summary>
        internal static string add_hh {
            get {
                return ResourceManager.GetString("add_hh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลสมาชิก.
        /// </summary>
        internal static string add_member {
            get {
                return ResourceManager.GetString("add_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นาที.
        /// </summary>
        internal static string add_mm {
            get {
                return ResourceManager.GetString("add_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มเงิน.
        /// </summary>
        internal static string add_money {
            get {
                return ResourceManager.GetString("add_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Add or remove programe.
        /// </summary>
        internal static string add_remove_programe {
            get {
                return ResourceManager.GetString("add_remove_programe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลสำเร็จ.
        /// </summary>
        internal static string add_success {
            get {
                return ResourceManager.GetString("add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลล้มเหลว.
        /// </summary>
        internal static string add_unsuccess {
            get {
                return ResourceManager.GetString("add_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มเติม.
        /// </summary>
        internal static string additional {
            get {
                return ResourceManager.GetString("additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แอดมิน.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Administrative tool.
        /// </summary>
        internal static string administrative_tool {
            get {
                return ResourceManager.GetString("administrative_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหลังเปิดใช้งาน.
        /// </summary>
        internal static string after_use {
            get {
                return ResourceManager.GetString("after_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาท.
        /// </summary>
        internal static string baht {
            get {
                return ResourceManager.GetString("baht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเกิด วัน เดือน ปี (ค.ศ.).
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งานโบนัสเติมเงิน.
        /// </summary>
        internal static string bonus {
            get {
                return ResourceManager.GetString("bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้มโบนัส.
        /// </summary>
        internal static string bonus_point {
            get {
                return ResourceManager.GetString("bonus_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เติมเงิน.
        /// </summary>
        internal static string bonus_top_up {
            get {
                return ResourceManager.GetString("bonus_top_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มียอดเงินนี้แล้ว.
        /// </summary>
        internal static string bonus_topup_unsuccess {
            get {
                return ResourceManager.GetString("bonus_topup_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีแต้มโบนัสนี้แล้ว.
        /// </summary>
        internal static string bonus_unsuccess {
            get {
                return ResourceManager.GetString("bonus_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการปิดโปรแกรมแน่หรือไม่?.
        /// </summary>
        internal static string cancel_confirm {
            get {
                return ResourceManager.GetString("cancel_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถลบข้อมูลนี้ได้.
        /// </summary>
        internal static string cant_del {
            get {
                return ResourceManager.GetString("cant_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถแก้ไขข้อมูลนี่ได้.
        /// </summary>
        internal static string cant_edit {
            get {
                return ResourceManager.GetString("cant_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โบนัสนี้กำลังถูกใช้ ไม่มามารถแก้ไขแต้มโบนัสได้.
        /// </summary>
        internal static string cant_edit_bonus {
            get {
                return ResourceManager.GetString("cant_edit_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่นนี้กำลังถูกใช้ ไม่สามารถแก้ไขยอดเติมเงิน หรือแต้มโบนัสได้.
        /// </summary>
        internal static string cant_edit_promo {
            get {
                return ResourceManager.GetString("cant_edit_promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มนี้กำลังถูกใช้ ไม่สามารถแก้ไขค่าบริการได้.
        /// </summary>
        internal static string cant_edit_rate {
            get {
                return ResourceManager.GetString("cant_edit_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable CD-Rom.
        /// </summary>
        internal static string cd_rom {
            get {
                return ResourceManager.GetString("cd_rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Shutdown.
        /// </summary>
        internal static string client_shutdown {
            get {
                return ResourceManager.GetString("client_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Cafe.
        /// </summary>
        internal static string close_cafe {
            get {
                return ResourceManager.GetString("close_cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Client.
        /// </summary>
        internal static string close_client {
            get {
                return ResourceManager.GetString("close_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันรหัสผ่าน.
        /// </summary>
        internal static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเชื่อมต่อผิดพลาด.
        /// </summary>
        internal static string conn_unsuccess {
            get {
                return ResourceManager.GetString("conn_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically shutdown all client at (HH:mm).
        /// </summary>
        internal static string content_on_off {
            get {
                return ResourceManager.GetString("content_on_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on / off the timer.
        /// </summary>
        internal static string content_title {
            get {
                return ResourceManager.GetString("content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ควบคุม.
        /// </summary>
        internal static string control {
            get {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string control_panel {
            get {
                return ResourceManager.GetString("control_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คูปอง.
        /// </summary>
        internal static string coupon {
            get {
                return ResourceManager.GetString("coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string coupon_exp {
            get {
                return ResourceManager.GetString("coupon_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อคูปอง.
        /// </summary>
        internal static string coupon_name {
            get {
                return ResourceManager.GetString("coupon_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อขึ้นต้นคูปอง.
        /// </summary>
        internal static string coupon_name_s {
            get {
                return ResourceManager.GetString("coupon_name_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีชื่อคูปองนี้แล้ว.
        /// </summary>
        internal static string coupon_name_unsuccess {
            get {
                return ResourceManager.GetString("coupon_name_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        internal static string coupon_password {
            get {
                return ResourceManager.GetString("coupon_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        internal static string coupon_price {
            get {
                return ResourceManager.GetString("coupon_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานคูปอง.
        /// </summary>
        internal static string coupon_report {
            get {
                return ResourceManager.GetString("coupon_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        internal static string coupon_time {
            get {
                return ResourceManager.GetString("coupon_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินคงเหลือ.
        /// </summary>
        internal static string coupon_total_amount {
            get {
                return ResourceManager.GetString("coupon_total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้.
        /// </summary>
        internal static string coupon_username {
            get {
                return ResourceManager.GetString("coupon_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดระบุจำนวนที่ต้องการสร้าง.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนที่สร้าง.
        /// </summary>
        internal static string create_amount {
            get {
                return ResourceManager.GetString("create_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างคูปอง.
        /// </summary>
        internal static string create_coupon {
            get {
                return ResourceManager.GetString("create_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สร้าง.
        /// </summary>
        internal static string create_date {
            get {
                return ResourceManager.GetString("create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สร้าง ถึง วัน เดือน ปี(ค.ศ.).
        /// </summary>
        internal static string create_end {
            get {
                return ResourceManager.GetString("create_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สร้าง ตั้งแต่ วัน เดือน ปี(ค.ศ.).
        /// </summary>
        internal static string create_start {
            get {
                return ResourceManager.GetString("create_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำกัดเงินยืม.
        /// </summary>
        internal static string credit_limit {
            get {
                return ResourceManager.GetString("credit_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฐานข้อมูล.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Date and Time.
        /// </summary>
        internal static string date_time {
            get {
                return ResourceManager.GetString("date_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนี้.
        /// </summary>
        internal static string debt {
            get {
                return ResourceManager.GetString("debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีหนี้ (บาท).
        /// </summary>
        internal static string debt_check {
            get {
                return ResourceManager.GetString("debt_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการลบข้อมูลแน่หรือไม่.
        /// </summary>
        internal static string del_confirm {
            get {
                return ResourceManager.GetString("del_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบคูปอง.
        /// </summary>
        internal static string del_coupon {
            get {
                return ResourceManager.GetString("del_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลล้มเหลว.
        /// </summary>
        internal static string del_false {
            get {
                return ResourceManager.GetString("del_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มผู้ใช้กำลังถูกใช้งาน.
        /// </summary>
        internal static string del_false_in_use {
            get {
                return ResourceManager.GetString("del_false_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบสมาชิก.
        /// </summary>
        internal static string del_member {
            get {
                return ResourceManager.GetString("del_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลสำเร็จ.
        /// </summary>
        internal static string del_success {
            get {
                return ResourceManager.GetString("del_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สิ้นสุด วัน เดือน ปี (ค.ศ.).
        /// </summary>
        internal static string e_date {
            get {
                return ResourceManager.GetString("e_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลคูปอง.
        /// </summary>
        internal static string edit_coupon {
            get {
                return ResourceManager.GetString("edit_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลสมาชิก.
        /// </summary>
        internal static string edit_member {
            get {
                return ResourceManager.GetString("edit_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลสำเร็จ.
        /// </summary>
        internal static string edit_success {
            get {
                return ResourceManager.GetString("edit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลล้มเหลว.
        /// </summary>
        internal static string edit_unsuccess {
            get {
                return ResourceManager.GetString("edit_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถึง วัน เดือน ปี (ค.ศ.).
        /// </summary>
        internal static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดระบุข้อมูล.
        /// </summary>
        internal static string enter_info {
            get {
                return ResourceManager.GetString("enter_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ตรงกับฐานข้อมูล.
        /// </summary>
        internal static string enter_match {
            get {
                return ResourceManager.GetString("enter_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านใหม่ไม่ตรงกัน.
        /// </summary>
        internal static string enter_match_pass {
            get {
                return ResourceManager.GetString("enter_match_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดระบุชื่อผู้ใช้ และรหัสผ่าน.
        /// </summary>
        internal static string enter_user_pass {
            get {
                return ResourceManager.GetString("enter_user_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมดอายุภายใน.
        /// </summary>
        internal static string exp_date {
            get {
                return ResourceManager.GetString("exp_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมมดอายุ ถึง วัน เดือน ปี(ค.ศ.).
        /// </summary>
        internal static string exp_end {
            get {
                return ResourceManager.GetString("exp_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ ตั้งแต่ วัน เดือน ปี(ค.ศ.).
        /// </summary>
        internal static string exp_start {
            get {
                return ResourceManager.GetString("exp_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินฟรี(บาท).
        /// </summary>
        internal static string free_money {
            get {
                return ResourceManager.GetString("free_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เติมเงินฟรี.
        /// </summary>
        internal static string free_top_up {
            get {
                return ResourceManager.GetString("free_top_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มผู้ใช้.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อกลุ่ม.
        /// </summary>
        internal static string group_name {
            get {
                return ResourceManager.GetString("group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีชื่อกลุ่มนี่แล้ว.
        /// </summary>
        internal static string group_name_unsuccess {
            get {
                return ResourceManager.GetString("group_name_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าบริการต่อชั่วโมง.
        /// </summary>
        internal static string group_rate {
            get {
                return ResourceManager.GetString("group_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชั่วโมง.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซม..
        /// </summary>
        internal static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าบริการต่อชั่วโมง.
        /// </summary>
        internal static string hr_money {
            get {
                return ResourceManager.GetString("hr_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา(บาท).
        /// </summary>
        internal static string hr_price {
            get {
                return ResourceManager.GetString("hr_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าบริการต่อชั่วโมง(บาท).
        /// </summary>
        internal static string hr_rate {
            get {
                return ResourceManager.GetString("hr_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบัตรประชาชน.
        /// </summary>
        internal static string id_card {
            get {
                return ResourceManager.GetString("id_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ใช้งานตั้งแต่ วัน เดือน ปี (ค.ศ.).
        /// </summary>
        internal static string inactive_after {
            get {
                return ResourceManager.GetString("inactive_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายได้.
        /// </summary>
        internal static string income {
            get {
                return ResourceManager.GetString("income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานรายได้.
        /// </summary>
        internal static string income_report {
            get {
                return ResourceManager.GetString("income_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืมเงิน.
        /// </summary>
        internal static string lend {
            get {
                return ResourceManager.GetString("lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Lock PC.
        /// </summary>
        internal static string lock_pc {
            get {
                return ResourceManager.GetString("lock_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การใช้งาน.
        /// </summary>
        internal static string log_history {
            get {
                return ResourceManager.GetString("log_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล็อกอินโดย.
        /// </summary>
        internal static string login_with {
            get {
                return ResourceManager.GetString("login_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Lock off PC.
        /// </summary>
        internal static string logoff_pc {
            get {
                return ResourceManager.GetString("logoff_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าหลัก.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินยืมเกินจำนวนที่จำกัด.
        /// </summary>
        internal static string max_credit {
            get {
                return ResourceManager.GetString("max_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนที่ชำระเกินจำนวนหนี้ที่มี.
        /// </summary>
        internal static string max_debt {
            get {
                return ResourceManager.GetString("max_debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มียอดเงินไม่เกิน (บาท).
        /// </summary>
        internal static string maximum_balance {
            get {
                return ResourceManager.GetString("maximum_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิก.
        /// </summary>
        internal static string member {
            get {
                return ResourceManager.GetString("member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิก / คูปอง.
        /// </summary>
        internal static string member_coupon {
            get {
                return ResourceManager.GetString("member_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string member_lastname {
            get {
                return ResourceManager.GetString("member_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string member_name {
            get {
                return ResourceManager.GetString("member_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีชื่อสมาชิกนี้แล้ว.
        /// </summary>
        internal static string member_name_unsuccess {
            get {
                return ResourceManager.GetString("member_name_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานสมาชิก.
        /// </summary>
        internal static string member_report {
            get {
                return ResourceManager.GetString("member_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินคงเหลือ.
        /// </summary>
        internal static string member_rr_amount {
            get {
                return ResourceManager.GetString("member_rr_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินคงเหลือ.
        /// </summary>
        internal static string member_total_amount {
            get {
                return ResourceManager.GetString("member_total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้.
        /// </summary>
        internal static string member_username {
            get {
                return ResourceManager.GetString("member_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to น..
        /// </summary>
        internal static string mn {
            get {
                return ResourceManager.GetString("mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการใช้เงิน.
        /// </summary>
        internal static string money_history {
            get {
                return ResourceManager.GetString("money_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Network connection.
        /// </summary>
        internal static string network_conn {
            get {
                return ResourceManager.GetString("network_conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านใหม่.
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเล่น.
        /// </summary>
        internal static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        internal static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        internal static string no_info {
            get {
                return ResourceManager.GetString("no_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ได้อยู่ในกลุ่มที่เติมเงินได้.
        /// </summary>
        internal static string not_group_can_top_up {
            get {
                return ResourceManager.GetString("not_group_can_top_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พนักงาน.
        /// </summary>
        internal static string officer {
            get {
                return ResourceManager.GetString("officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านเดิม.
        /// </summary>
        internal static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานการใช้งาน.
        /// </summary>
        internal static string online_history_report {
            get {
                return ResourceManager.GetString("online_history_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาคงเหลือ.
        /// </summary>
        internal static string online_remaining_time {
            get {
                return ResourceManager.GetString("online_remaining_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        internal static string online_s_date {
            get {
                return ResourceManager.GetString("online_s_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเริ่ม.
        /// </summary>
        internal static string online_s_datetime {
            get {
                return ResourceManager.GetString("online_s_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        internal static string online_s_time {
            get {
                return ResourceManager.GetString("online_s_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่ใช้ไป.
        /// </summary>
        internal static string online_use_time {
            get {
                return ResourceManager.GetString("online_use_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อคูปอง.
        /// </summary>
        internal static string op_c_name {
            get {
                return ResourceManager.GetString("op_c_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มต้น.
        /// </summary>
        internal static string op_c_s_date {
            get {
                return ResourceManager.GetString("op_c_s_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตั้งค่า.
        /// </summary>
        internal static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งค่าคูปอง.
        /// </summary>
        internal static string option_coupon {
            get {
                return ResourceManager.GetString("option_coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนรหัสผ่าน.
        /// </summary>
        internal static string password_change {
            get {
                return ResourceManager.GetString("password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระหนี้.
        /// </summary>
        internal static string pay_debt {
            get {
                return ResourceManager.GetString("pay_debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการใช้ PC.
        /// </summary>
        internal static string pc_history {
            get {
                return ResourceManager.GetString("pc_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล PC.
        /// </summary>
        internal static string pc_info {
            get {
                return ResourceManager.GetString("pc_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเครื่อง.
        /// </summary>
        internal static string pc_name {
            get {
                return ResourceManager.GetString("pc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะเครื่อง.
        /// </summary>
        internal static string pc_status {
            get {
                return ResourceManager.GetString("pc_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string permission {
            get {
                return ResourceManager.GetString("permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Management.
        /// </summary>
        internal static string power_management {
            get {
                return ResourceManager.GetString("power_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string pricing {
            get {
                return ResourceManager.GetString("pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดใช้งานสิทธิพิเศษ.
        /// </summary>
        internal static string promo {
            get {
                return ResourceManager.GetString("promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อโปรโปรชั่น.
        /// </summary>
        internal static string promo_name {
            get {
                return ResourceManager.GetString("promo_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีชื่อโปรโมชั่นนี้แล้ว.
        /// </summary>
        internal static string promo_name_unsuccess {
            get {
                return ResourceManager.GetString("promo_name_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินโบนัส.
        /// </summary>
        internal static string promo_rate {
            get {
                return ResourceManager.GetString("promo_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้มโบนัส.
        /// </summary>
        internal static string promo_rate_point {
            get {
                return ResourceManager.GetString("promo_rate_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่น.
        /// </summary>
        internal static string promotion {
            get {
                return ResourceManager.GetString("promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Regional and language setting.
        /// </summary>
        internal static string regional_language_setting {
            get {
                return ResourceManager.GetString("regional_language_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable registry editor.
        /// </summary>
        internal static string registry_editor {
            get {
                return ResourceManager.GetString("registry_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินจริงคงเหลือ.
        /// </summary>
        internal static string remaining_amount {
            get {
                return ResourceManager.GetString("remaining_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินฟรีคงเหลือ.
        /// </summary>
        internal static string remaining_free_amount {
            get {
                return ResourceManager.GetString("remaining_free_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชั่วโมงคงเหลือ.
        /// </summary>
        internal static string remaining_hh {
            get {
                return ResourceManager.GetString("remaining_hh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นาทีคงเหลือ.
        /// </summary>
        internal static string remaining_mm {
            get {
                return ResourceManager.GetString("remaining_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินคงเหลือ.
        /// </summary>
        internal static string remaining_money {
            get {
                return ResourceManager.GetString("remaining_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้มคงเหลือ.
        /// </summary>
        internal static string remaining_point {
            get {
                return ResourceManager.GetString("remaining_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาคงเหลือ.
        /// </summary>
        internal static string remaining_time {
            get {
                return ResourceManager.GetString("remaining_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงาน.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding.
        /// </summary>
        internal static string rounding {
            get {
                return ResourceManager.GetString("rounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มต้น วัน เดือน ปี (ค.ศ.).
        /// </summary>
        internal static string s_date {
            get {
                return ResourceManager.GetString("s_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึก.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวเลือกการค้นหา.
        /// </summary>
        internal static string search_help {
            get {
                return ResourceManager.GetString("search_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกทั้งหมด.
        /// </summary>
        internal static string select_check {
            get {
                return ResourceManager.GetString("select_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกข้อมูลที่ต้องการลบ.
        /// </summary>
        internal static string select_info {
            get {
                return ResourceManager.GetString("select_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Shutdown and Restart.
        /// </summary>
        internal static string shutdown_restart {
            get {
                return ResourceManager.GetString("shutdown_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พนักงาน.
        /// </summary>
        internal static string staff {
            get {
                return ResourceManager.GetString("staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string staff_lastname {
            get {
                return ResourceManager.GetString("staff_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string staff_name {
            get {
                return ResourceManager.GetString("staff_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีชื่อผู้ใช้นี้แล้ว.
        /// </summary>
        internal static string staff_name_unsuccess {
            get {
                return ResourceManager.GetString("staff_name_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเล่น.
        /// </summary>
        internal static string staff_nickname {
            get {
                return ResourceManager.GetString("staff_nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นับจากวันที่ถูกสร้าง.
        /// </summary>
        internal static string start_create_date {
            get {
                return ResourceManager.GetString("start_create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งแต่ วัน เดือน ปี (ค.ศ.).
        /// </summary>
        internal static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นับจากวันที่ถูกใช้งาน.
        /// </summary>
        internal static string start_first_use {
            get {
                return ResourceManager.GetString("start_first_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเริ่ม.
        /// </summary>
        internal static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งานกลุ่มผู้ใช้.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Swicth User.
        /// </summary>
        internal static string swicth_user {
            get {
                return ResourceManager.GetString("swicth_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide System panel applet.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable task manager.
        /// </summary>
        internal static string task_manager {
            get {
                return ResourceManager.GetString("task_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทร.
        /// </summary>
        internal static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แน่ใจหรือไม่?.
        /// </summary>
        internal static string title_confirm {
            get {
                return ResourceManager.GetString("title_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สำเร็จ.
        /// </summary>
        internal static string title_false {
            get {
                return ResourceManager.GetString("title_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเร็จ.
        /// </summary>
        internal static string title_success {
            get {
                return ResourceManager.GetString("title_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เติมเงิน.
        /// </summary>
        internal static string top_up {
            get {
                return ResourceManager.GetString("top_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินที่เติม.
        /// </summary>
        internal static string top_up_amount {
            get {
                return ResourceManager.GetString("top_up_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานการเติมเงิน.
        /// </summary>
        internal static string top_up_report {
            get {
                return ResourceManager.GetString("top_up_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินทั้งหมด(บาท).
        /// </summary>
        internal static string total_amount {
            get {
                return ResourceManager.GetString("total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินฟรีทั้งหมด.
        /// </summary>
        internal static string total_free_amount {
            get {
                return ResourceManager.GetString("total_free_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชั่วโมง.
        /// </summary>
        internal static string total_hh {
            get {
                return ResourceManager.GetString("total_hh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นาที.
        /// </summary>
        internal static string total_mm {
            get {
                return ResourceManager.GetString("total_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โอนเงิน.
        /// </summary>
        internal static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทผู้ใช้.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        internal static string type_name {
            get {
                return ResourceManager.GetString("type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง.
        /// </summary>
        internal static string unsuccess {
            get {
                return ResourceManager.GetString("unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินที่ใช้ไป.
        /// </summary>
        internal static string use_amount {
            get {
                return ResourceManager.GetString("use_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่ใช้ไป.
        /// </summary>
        internal static string use_time {
            get {
                return ResourceManager.GetString("use_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide User acount.
        /// </summary>
        internal static string user_account {
            get {
                return ResourceManager.GetString("user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้นี้ หมดอายุการใช้งาน.
        /// </summary>
        internal static string user_expire {
            get {
                return ResourceManager.GetString("user_expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มผู้ใช้.
        /// </summary>
        internal static string user_group {
            get {
                return ResourceManager.GetString("user_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการใช้งาน.
        /// </summary>
        internal static string user_history {
            get {
                return ResourceManager.GetString("user_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ใช้.
        /// </summary>
        internal static string user_info {
            get {
                return ResourceManager.GetString("user_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดรอ.
        /// </summary>
        internal static string wait_pls {
            get {
                return ResourceManager.GetString("wait_pls", resourceCulture);
            }
        }
    }
}
