//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMS_Client.Res.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICMS_Client.Res.language.resLang", typeof(resLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล็อกหน้าจอ.
        /// </summary>
        internal static string _lock {
            get {
                return ResourceManager.GetString("lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชี.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาทั้งหมด.
        /// </summary>
        internal static string all_time {
            get {
                return ResourceManager.GetString("all_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โบนัส.
        /// </summary>
        internal static string b_time {
            get {
                return ResourceManager.GetString("b_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเดือนปี/เกิด.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าบริการ.
        /// </summary>
        internal static string c_time {
            get {
                return ResourceManager.GetString("c_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเชื่อมต่อผิดพลาด ลองใหม่อีกครั้ง.
        /// </summary>
        internal static string conn_false {
            get {
                return ResourceManager.GetString("conn_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สร้าง.
        /// </summary>
        internal static string create_date {
            get {
                return ResourceManager.GetString("create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนี้คงเหลือ.
        /// </summary>
        internal static string debt {
            get {
                return ResourceManager.GetString("debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สิ้นสุด.
        /// </summary>
        internal static string e_date {
            get {
                return ResourceManager.GetString("e_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูลสมาชิก.
        /// </summary>
        internal static string edit_account {
            get {
                return ResourceManager.GetString("edit_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลล์.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดระบุข้อมูล.
        /// </summary>
        internal static string enter_info {
            get {
                return ResourceManager.GetString("enter_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มผู้ใช้.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสประจำตัวประชาชน.
        /// </summary>
        internal static string id_card {
            get {
                return ResourceManager.GetString("id_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่เหลือ.
        /// </summary>
        internal static string l_time {
            get {
                return ResourceManager.GetString("l_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การใช้งาน.
        /// </summary>
        internal static string log_history {
            get {
                return ResourceManager.GetString("log_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้ หรือรหัสผ่านไม่ถูกต้อง.
        /// </summary>
        internal static string login_false {
            get {
                return ResourceManager.GetString("login_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเล่น.
        /// </summary>
        internal static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่น.
        /// </summary>
        internal static string promotion {
            get {
                return ResourceManager.GetString("promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้มโบนัส.
        /// </summary>
        internal static string promotion_bonus {
            get {
                return ResourceManager.GetString("promotion_bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสโปรโมชั่น.
        /// </summary>
        internal static string promotion_id {
            get {
                return ResourceManager.GetString("promotion_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินโบนัส.
        /// </summary>
        internal static string promotion_money {
            get {
                return ResourceManager.GetString("promotion_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อโปรโมชั่น.
        /// </summary>
        internal static string promotion_name {
            get {
                return ResourceManager.GetString("promotion_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินคงเหลือ.
        /// </summary>
        internal static string remaining_amount {
            get {
                return ResourceManager.GetString("remaining_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินฟรีคงเหลือ.
        /// </summary>
        internal static string remaining_free_amount {
            get {
                return ResourceManager.GetString("remaining_free_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้มคงเหลือ.
        /// </summary>
        internal static string remaining_point {
            get {
                return ResourceManager.GetString("remaining_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มต้น.
        /// </summary>
        internal static string s_date {
            get {
                return ResourceManager.GetString("s_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเริ่ม.
        /// </summary>
        internal static string start_datetime {
            get {
                return ResourceManager.GetString("start_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเร็จ.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        internal static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สำเร็จ.
        /// </summary>
        internal static string title_false {
            get {
                return ResourceManager.GetString("title_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สำเร็จ.
        /// </summary>
        internal static string title_unsuccess {
            get {
                return ResourceManager.GetString("title_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินที่เติม.
        /// </summary>
        internal static string top_up_amount {
            get {
                return ResourceManager.GetString("top_up_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินฟรีทั้งหมด.
        /// </summary>
        internal static string total_free_amount {
            get {
                return ResourceManager.GetString("total_free_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่ใช้.
        /// </summary>
        internal static string u_time {
            get {
                return ResourceManager.GetString("u_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สำเร็จ.
        /// </summary>
        internal static string unsuccess {
            get {
                return ResourceManager.GetString("unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินที่ใช้ไป.
        /// </summary>
        internal static string use_amount {
            get {
                return ResourceManager.GetString("use_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ใช้.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
